### PR TITLE
issue with black lines around videos

### PR DESCRIPTION
**Pull request by tomallpress**
an issue has been intermittently occuring to do with black lines
appearing on the sides of some videos that sit inside the video player.
this was because the video player had a black background. I've now set
the background to transparent to avoid this.

### CODE REVIEW

**Comment by taylortom** [comment]
+1

**Comment by zenduo** [comment]
+1

**Comment by zenduo** [comment]
Is this not an issue with ".mejs-container" rather than ".mejs-container iframe"?

**Comment by tomallpress** [comment]
yep i think you're right @zenduo. I've moved it up to .mejs-container.

**Comment by taylortom** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
