### PR TITLE
Update MediaElement to v2.20.1

### PR DESCRIPTION
**Pull request by tomgreenfield**
Switched to full version of `mediaelement-and-player.js` in preparation for @oliverfoster’s patch to resolve https://github.com/adaptlearning/adapt_framework/issues/983.

issue: https://github.com/adaptlearning/adapt_framework/issues/989

### CODE REVIEW

**Comment by oliverfoster** [comment]
+1 all works as expected. once in we've got fixes for full screen and making closed captions button accessible

**Comment by brian-learningpool** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by moloko** [comment]
+1 also tested with youtube and vimeo as the source, all still seems to work

**Pull request merged**
