### PR TITLE
Fix: Firefox fullscreen api (fixes #239)

### LINKED ISSUE #239: In Firefox, it's necessary to press Esc twice to completely exit fullscreen
### Subject of the issue/enhancement/features
In Firefox, if you go into full screen mode whilst playing video and then try to exit by pressing `<Esc>`, the media component goes into the same 'fake fullscreen mode' it uses if you press the fullscreen button before initiating playback.

If you use the fullscreen button in the player controls to exit fullscreen mode, it works fine.

### Your environment
* FW (tried both v5.3.0 and v5.6.1) and media component (v5.0.1)
* Firefox v80
* Win 10

### Steps to reproduce
Easiest method is to try it out in the [media component on the v5demo course](https://adaptlearning.github.io/v5demo/#/id/c-40). Click play then click the fullscreen button. Then press `<Esc>`.

### Expected behaviour
Pressing `<Esc>` should take you straight back to the media component within the course page, as it does for other browsers (and as it does if you use the fullscreen button on the player controls).

### Actual behaviour
You have to press `<Esc>` a second time, at which point, the following error is displayed before it then goes back to displaying the media component in the page.
image

### Screenshots (if you can)
image

### PR DESCRIPTION
**Pull request by oliverfoster**
fiex #239 

### Fix
* Firefox uses native fullscreen api where available

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by swashbuck** [comment]
I'm getting a console error when in fullscreen and pressing the ESC key to exit fullscreen.

```
Uncaught (in promise) TypeError: Not in fullscreen mode
    cancelFullScreen mediaView.js:103
    exitFullScreen mediaelement-and-player.js:4674
    fullscreenChanged mediaelement-and-player.js:4346
```

### Environment
- Firefox 112.0.1 
- Mac 11.7.6 

### Branches / versions
- Framework 5.28.9
- Media issue/239

**Comment by oliverfoster** [comment]
Cool. Will check on mac. Thanks.

**Comment by StuartNicholls** [comment]
@oliverfoster on Mac I'm not seeing it go in to Full screen, the vid increases to the browser size but the browser remains at the size before pressing the button. I also get the same console error

`Uncaught (in promise) TypeError: Not in fullscreen mode`

**Comment by oliverfoster** [comment]
* Firefox, obvs, I meant 🔥🦊

**Review by joe-allen-89 — APPROVED** [review]
👍 tested with multiple browsers all working as expected, no errors.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by kirsty-hames — APPROVED** [review]
Works as expected testing on Mac FF

**Pull request merged**
