### PR TITLE
Tidied up validation on closed captions object

### PR DESCRIPTION
**Pull request by brian-learningpool**
Both 'src' and 'srcLang' should be required.

### CODE REVIEW

**Comment by brian-learningpool** [comment]
Resolves https://github.com/adaptlearning/adapt_framework/issues/1191.

Referenced here also: https://github.com/adaptlearning/adapt_framework/issues/1192.

**Comment by hrajotia** [comment]
+1

**Comment by chetan-hajare** [comment]
+1

**Comment by moloko** [comment]
+1

**Pull request merged**
