### PR TITLE
Update schema and include globals

### PR DESCRIPTION
**Pull request by dancgray**

### CODE REVIEW

**Comment by dancgray** [comment]
See https://github.com/adaptlearning/adapt-contrib-media/issues/97 still need to add vimeo/utube URL

**Comment by dancgray** [comment]
I'm not sure these global varaiable are used anymore:
_accessibility._ariaLabels.menuViewButton
_accessibility._ariaLabels.menuBack
_accessibility._ariaLabels.menuIndicatorHeading

**Comment by brian-learningpool** [comment]
+1 for the schema changes -- good to finally have the Youtube option too!

**Comment by moloko** [comment]
+1

**Comment by taylortom** [comment]
+1

**Comment by taylortom** [comment]
@oliverfoster can you comment on @dancgrey's question about the ARIA labels?

**Comment by oliverfoster** [comment]
@dancgray that's right, although i'm going to add visited : "visited"

**Pull request merged**
