### PR TITLE
bugfix/hide-controls: default to hide controls

### PR DESCRIPTION
**Pull request by oliverfoster**
hide controls on default and with mouseover unless otherwise specified or accessibility is on

### CODE REVIEW

**Comment by moloko** [comment]
hmmm... although I can see this is setting those two properties correctly there doesn't seem to be much visible impact, no matter what I have them set to...! But then I get the same result with the code that's current in master so I guess... +1?!

**Comment by moloko** [comment]
+1

**Comment by dancgray** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
