### PR TITLE
issue/2799 Remove redundant behaviour

### PR DESCRIPTION
**Pull request by oliverfoster**
requires https://github.com/adaptlearning/adapt-contrib-core/pull/84
part of https://github.com/adaptlearning/adapt_framework/issues/2799

### Changed
* Switched to components.register from Adapt.register
* Use `offlineStorage`, `a11y`, `device` and `logging` directly
* Switched to `equals` helper from `if_value_equals`

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by joe-allen-89 — CHANGES_REQUESTED** [review]
Need to remove the unused import log from line 8, and duplicate offlineStorage from line 9.

**Comment by oliverfoster** [comment]
> Need to remove the unused import log from line 8, and duplicate offlineStorage from line 9.

Which file? @joe-allen-89

**Comment by joe-allen-89** [comment]
> > Need to remove the unused import log from line 8, and duplicate offlineStorage from line 9.
> 
> Which file? @joe-allen-89

@oliverfoster should have included that, mediaView.js

**Pull request merged**
