### PR TITLE
#898 Set complete on transcript as default

### PR DESCRIPTION
**Pull request by oliverfoster**
* Have removed dependency on accessibility
* Set complete on transcript as default
* Allowed user to override in settings
* Updated schema to match

### CODE REVIEW

**Comment by moloko** [comment]
+1

**Comment by moloko** [comment]
oh, if you have a sec could you amend the README as part of this PR? If not don't worry will change once merged

**Comment by oliverfoster** [comment]
Sorted

**Comment by brian-learningpool** [comment]
+1

**Comment by dancgray** [comment]
+1

**Pull request merged**
