### PR TITLE
issue-1239: enabled spacebar on timeline

### PR DESCRIPTION
**Pull request by oliverfoster**
https://github.com/adaptlearning/adapt_framework/issues/1239

added play/pause toggle on spacebar on timeline

### CODE REVIEW

**Comment by chetan-hajare** [comment]
Just tested, the issue seems not completely resolved.
If the video is playing and "spacebar" key is pressed, video pauses and plays again.
If the video is paused and "spacebar" key is pressed, video plays and pauses again.

**Comment by oliverfoster** [comment]
yea, i built this against an older version of the media element. just need to make sure the issue has been resolved by the latest media player before i delete this entirely.

can you test just the latest media component?

**Comment by chetan-hajare** [comment]
Sure

**Comment by chetan-hajare** [comment]
yea, it is resolved 👍

**Comment by oliverfoster** [comment]
cool 
https://github.com/adaptlearning/adapt_framework/issues/1244

**Pull request closed without merging**
