### PR TITLE
Version 2.0.5 pre-release

### PR DESCRIPTION
**Pull request by brian-learningpool**
Browser testing:

- [x] IE 8
YouTube control bar missing
YouTube/Vimeo does not track completion
- [x] IE 9 (Vimeo: ‘Sorry This video does not exist’ - seems to be a Vimeo issue)
- [x] IE 10
- [x] IE 11
- [x] Edge
- [x] Firefox
- [x] Chrome
- [x] iOS
- [x] Android

### CODE REVIEW

**Comment by moloko** [comment]
the 'ended' completion event is not working any more for Vimeo

**Comment by moloko** [comment]
Aside from https://github.com/adaptlearning/adapt_framework/issues/1212, Firefox seems fine. I did have one instance of the YouTube video not showing a poster image but I haven't been able to replicate.

**Comment by brian-learningpool** [comment]
I'm going to try to get a better solution for 18ba283.

**Comment by oliverfoster** [comment]
That DOMException is fine. Actually, it's unavoidable in some cases.

The play is executed to preload the video and help get the full metadata etc, but sometime you don't want the video to actually start playing. The DOMException is a result of calling "play();pause();". I wouldn't worry about it.

**Comment by moloko** [comment]
+1

**Pull request merged**
