### PR TITLE
issue/#2024: Video controls disappear in iOS 11

### PR DESCRIPTION
**Pull request by boonier**
fixes https://github.com/adaptlearning/adapt_framework/issues/2024

### CODE REVIEW

**Comment by tomgreenfield** [comment]
Thanks for the fix, @boonier!

Would you mind moving the style to our override file, [`media.less`](https://github.com/adaptlearning/adapt-contrib-media/blob/master/less/media.less), so that `mep.less` remains a carbon copy of Media Element's CSS?

**Comment by boonier** [comment]
This is done @tomgreenfield

**Comment by moloko** [comment]
I do get this warning pop up in Visual Studio Code - can it safely be ignored? 
image

**Comment by moloko** [comment]
sorry ignore me - of course it can be ignored because this is extending (rather than overriding) the `.mejs-offscreen` class from mep.less... 

as you were!

**Pull request merged**
