### PR TITLE
media : removed IE8 hack

### PR DESCRIPTION
**Pull request by akshay-bhavsar**

### CODE REVIEW

**Comment by moloko** [comment]
@sarveshwar-gavhane good spot! @akshay-bhavsar please remove the IE9 check as suggested

**Comment by moloko** [comment]
**as with all of these, please leave unmerged for now**

**Comment by oliverfoster** [comment]
does the purge function need to go?

**Comment by oliverfoster** [comment]
according to the ticket the issue showed up in IE11 and was solved by Crockfords IE6/IE7 fix.... so,let's leave it for the moment. @tomgreenfield be wary of memory leaks with the next version of mejs.
here is the original issue https://github.com/adaptlearning/adapt_framework/issues/1223

**Pull request merged**
