### PR TITLE
Fix: Chrome automatically exits full screen video if zoom is not 100% (fixes #255)

### LINKED ISSUE #255: Chrome automatically exits full screen video if zoom is not 100%
### Subject of the issue
**Chrome** automatically exits full screen video if zoom is not 100%.

https://github.com/mediaelement/mediaelement/issues/2644

### Your environment
* Framework 5.25.1
* adapt-contrib-media 6.3.0
* Chrome 110.0.5481.177
* Mac 11.7.4 Big Sur

### Steps to reproduce
To recreate in **Chrome**:

- View a course in an iframe (ex. in the CSOD course popup or using the attached HTML file).
- Navigate to a page with a Media component
- Zoom out to 90%.
- Click the full screen button. 

### Expected behaviour
Video should go full screen and remain full screen.

### Actual behaviour
Chrome flashes to full screen but then quickly exits back to normal view.

### PR DESCRIPTION
**Pull request by swashbuck**
Fixes #255 

### Fix
* Removes a fix for Chrome versions 16 and below. This was causing the initial issue with fullscreen video.

### Testing
See #255

### CODE REVIEW

**Comment by oliverfoster** [comment]
Could you replace https://github.com/adaptlearning/adapt-contrib-media/blob/9d74d2ba3966fb7ca796f442639f6f0a169c3d6e/libraries/mediaelement-and-player.js#L4549

on
https://github.com/adaptlearning/adapt-contrib-media/blob/9d74d2ba3966fb7ca796f442639f6f0a169c3d6e/libraries/mediaelement-and-player.js#L4242

Like https://github.com/adaptlearning/adapt-contrib-media/blob/5289ff82e93d6ed44b7c2a6fe28f98bd9396a841/js/mediaView.js#L55-L79

please?

**Comment by swashbuck** [comment]
@oliverfoster I've moved the enterFullScreen override into the view. [d21dde8](https://github.com/adaptlearning/adapt-contrib-media/pull/256/commits/d21dde8fda39abe8402af6218d34f0dd6ee2cc5a)

**Review by oliverfoster — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by eleanor-heath — APPROVED** [review]

**Comment by oliverfoster** [comment]
@swashbuck the merge title has to follow convention in order to trigger an automatic release

https://github.com/adaptlearning/adapt-contrib-media/actions/runs/4512326627/jobs/7945615124

**Pull request merged**
