### PR TITLE
Accessibility merge

### PR DESCRIPTION
**Pull request by oliverfoster**

### CODE REVIEW

**Comment by taylortom** [comment]
+1

**Comment by dancgray** [comment]
+1, does .media-top-padding ever get used?

**Comment by oliverfoster** [comment]
Not automatically no. It has to be specified. Much like adding a < br > to the _body attribute (as it was in the component.json). Instead you'd need to add media-top-padding to the _classes attribute. It's only for when you need that extra padding to bring the media component inline with an adjacent text component.

**Comment by taylortom** [comment]
+1

**Comment by moloko** [comment]
+1

**Pull request merged**
